### PR TITLE
Added expense types, source tracking and gem updates

### PR DESCRIPTION
**Pull request by billsinc**
Added the ability to have expense types (d=dollars, m=mileage), track sender and updated some of the outdated gems.  It's been a fun learning experience so far and I expect to continue to add functionality so stay tuned for more pull requests.

### CODE REVIEW

**Comment by avand** [comment]
Hey @billsinc, this looks pretty good! Have you tested it against in the real world to confirm it all works?

**Comment by billsinc** [comment]
Yes, it seems to work just fine.

**Comment by avand** [comment]
Cool. We should probably get some tests going around this at some point but in the meantime... merged!

**Comment by billsinc** [comment]
Yes, new to rails so I don’t have much experience writing them.

**Comment by avand** [comment]
Technically speaking this isn't a Rails project but I understand what you mean. We'll get tests in here at some point, I'm sure.

**Comment by billsinc** [comment]
Sorry, yes Sinatra, I'm working on a rails one too, thanks.

**Pull request merged**
